apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  ports:
  - name: http
    nodePort: 31890
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: tomcat
  sessionAffinity: None
  type: LoadBalancer
